name = "Lucas Boyles"
description = "🐾 Dog Enthusiast 🤓 Nerd Proponent 🌽 Iowa Blue Dot"
keywords = "Lucas Boyles, Postblink, twitch, gaming, tech, nerd, music, Iowa, midwest, blue, blue dot"
image = "ai-me-sketch.jpg"
theme = "dark"
primary_color = "#324b50"
text_align = "center"
gtag_id = "GTM-MLMRBQ5"
base_url = "https://postblink.github.io"

<iframe src="https://player.twitch.tv/?channel=postblink&parent=www.example.com" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>

[[sections]]
title = "Links"
description = "Find Me On"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Twitch"
url = "https://twitch.tv/postblink"
[[sections.items]]
title = "YouTube"
url = "https://www.youtube.com/@postblink"
[[sections.items]]
title = "Instagram"
url = "https://instagram.com/postblink"
[[sections.items]]
title = "Writing"
url = "https://postblink.live"
